name: shared_storage
description: "Flutter plugin to work with external storage."
version: 0.4.2
homepage: https://github.com/lakscastro/shared-storage
repository: https://github.com/lakscastro/shared-storage
issue_tracker: https://github.com/lakscastro/shared-storage/issues
documentation: https://github.com/lakscastro/shared-storage

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  plugin:
    platforms:
      android:
        package: io.lakscastro.sharedstorage
        pluginClass: SharedStoragePlugin
