name: shared_storage
description: "Flutter plugin to work with external storage and privacy-friendly APIs."
version: 0.9.0
homepage: https://github.com/alexrintt/shared-storage
repository: https://github.com/alexrintt/shared-storage
issue_tracker: https://github.com/alexrintt/shared-storage/issues
documentation: https://github.com/alexrintt/shared-storage
funding:
  - https://donate.alexrintt.io
  - https://github.com/sponsors/alexrintt

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  mime: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  plugin:
    platforms:
      android:
        package: io.alexrintt.sharedstorage
        pluginClass: SharedStoragePlugin
