name: shared_storage
description: "ğŸ“ Flutter plugin to get Android shared folders like DCIM, Downloads, Video, Audio. Works with Android 4.1 (API Level 16+)"
version: 0.2.0
homepage: https://github.com/LaksCastro/shared-storage
repository: https://github.com/LaksCastro/shared-storage
issue_tracker: https://github.com/LaksCastro/shared-storage/issues
documentation: https://github.com/LaksCastro/shared-storage

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  permission_handler: ^8.1.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.lakscastro.sharedstorage
        pluginClass: SharedStoragePlugin
